// KMP-NativeCoroutines is intentionally not installed in this SKIE fixture.
// This recipe is retained as documentation for its existing adapter support.
//
// Kotlin:
//
// @NativeCoroutinesState
// val messageState: StateFlow<String>
//
// Swift:
//
// import KMPNativeCoroutinesAsync
//
// @KMPStateObject(
//     wrappedValue: BridgeExampleViewModel(),
//     adapters: .asyncSequence { viewModel in
//         asyncSequence(for: viewModel.messageStateFlow)
//     }
// )
// private var example
//
// Text(example.messageStateValue)
//
// `messageStateFlow` is the cancellable observation source.
// `messageStateValue` is the synchronous value generated by
// `@NativeCoroutinesState`. NativeFlow itself is not a value container and
// therefore must not conform to KMPValueProperty.
